## This workflow will build a .NET project
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: TransitNE
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Set connection string
        run: export TransitNEContextConnection="Server=(localdb)\\mssqllocaldb;Database=TransitNE;Trusted_Connection=True;MultipleActiveResultSets=true"

      - name: Start Application
        run: nohup dotnet ./publish/TransitNE.dll &

      - name: Wait for app to start
        run: sleep 10
          
      - name: Unit Tests
        run: dotnet test --configuration Release

      - name: Show selenium logs
        run: docker logs selenium

      - name: Clean up
        run: docker stop selenium
